async-task-executor:
  core-pool-size: 5
  max-pool-size: 5
  queue-capacity: 10

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
        generate_statistics: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem://localhost/~/template_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 5000
      validation-timeout: 3000
      initialization-fail-timeout: 1000
      maximum-pool-size: 10

logging:
  level:
    org.hibernate.SQL: DEBUG
