server:
  port: 8080
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  undertow:
    threads:
      io: 8
      worker: 256

spring:
  config:
    import: application-adapter.yml
  application:
    name: template-api
  jackson:
    property-naming-strategy: SNAKE_CASE

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
